export default function Head() {
    return (
        <>
            <title>Tutorial</title>
            <meta content="width=device-width, initial-scale=1" name="view-port"/>
            <meta name="description" content="Generated by lowk"/>
        </>
    )
}